import { DevtoolsProvider } from '@providers/devtools'
import { GitHubBanner, Refine } from '@refinedev/core'
import { RefineKbar, RefineKbarProvider } from '@refinedev/kbar'
import { RefineSnackbarProvider, notificationProvider } from '@refinedev/mui'
import routerProvider from '@refinedev/nextjs-router'
import { Metadata } from 'next'
import { cookies } from 'next/headers'
import React, { Suspense } from 'react'

import { ColorModeContextProvider } from '@contexts/color-mode'
import { authProvider } from '@providers/auth-provider'
import { dataProvider } from '@providers/data-provider'

const title = process.env.NEXT_PUBLIC_APP_NAME || 'Refine'

export const metadata: Metadata = {
  title: title,
  description: 'Generated by create refine app',
  icons: {
    icon: '/favicon.ico',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookieStore = cookies()
  const theme = cookieStore.get('theme')
  const defaultMode = theme?.value === 'dark' ? 'dark' : 'light'

  return (
    <html lang="en">
      <body>
        <Suspense>
          <GitHubBanner />
          <RefineKbarProvider>
            <ColorModeContextProvider defaultMode={defaultMode}>
              <RefineSnackbarProvider>
                <DevtoolsProvider>
                  <Refine
                    routerProvider={routerProvider}
                    authProvider={authProvider}
                    dataProvider={dataProvider}
                    notificationProvider={notificationProvider}
                    options={{
                      syncWithLocation: true,
                      warnWhenUnsavedChanges: true,
                      useNewQueryKeys: true,
                      projectId: 'XF0RGt-Wt2yKt-DwSc6H',
                    }}
                  >
                    {children}
                    <RefineKbar />
                  </Refine>
                </DevtoolsProvider>
              </RefineSnackbarProvider>
            </ColorModeContextProvider>
          </RefineKbarProvider>
        </Suspense>
      </body>
    </html>
  )
}
